version: '2'

services:

  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.0
    volumes:
      - /opt/docker/elasticstack/volumes/elasticsearch/usr/share/elasticsearch/data:/usr/share/elasticsearch/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
    volumes:
      - /opt/docker/elasticstack/volumes/elasticsearch/usr/share/elasticsearch/data:/usr/share/elasticsearch/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9200:9200
